src/Entity/Representation.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RepresentationRepository")
 * @ORM\Table(name="representations")
 */
class Representation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Show", inversedBy="representations")
     * @ORM\JoinColumn(nullable=false, name="show_id", referencedColumnName="id")
     */
    private $the_show;

    /**
     * @ORM\Column(type="datetime", name="schedule")
     */
    private $the_date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Location", inversedBy="representations")
     * @ORM\JoinColumn(name="location_id", referencedColumnName="id")
     */
    private $the_location;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reservation", mappedBy="representation")
     */
    private $reservations;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTheShow(): ?Show
    {
        return $this->the_show;
    }

    public function setTheShow(?Show $the_show): self
    {
        $this->the_show = $the_show;

        return $this;
    }

    public function getTheDate(): ?\DateTimeInterface
    {
        return $this->the_date;
    }

    public function setTheDate(\DateTimeInterface $the_date): self
    {
        $this->the_date = $the_date;

        return $this;
    }

    public function getTheLocation(): ?Location
    {
        return $this->the_location;
    }

    public function setTheLocation(?Location $the_location): self
    {
        $this->the_location = $the_location;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setRepresentation($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->contains($reservation)) {
            $this->reservations->removeElement($reservation);
            // set the owning side to null (unless already changed)
            if ($reservation->getRepresentation() === $this) {
                $reservation->setRepresentation(null);
            }
        }

        return $this;
    }
}

src/Entity/Show.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ShowRepository")
 * @ORM\Table(name="shows")
 */
class Show
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poster_url;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Location", inversedBy="bookable")
     */
    private $location;

    /**
     * @ORM\Column(type="boolean")
     */
    private $bookable;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Representation", mappedBy="the_show", orphanRemoval=true)
     */
    private $representations;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\ArtistType")
     */
    private $troupe;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="shows")
     */
    private $category;

    public function __construct()
    {
        $this->representations = new ArrayCollection();
        $this->troupe = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPosterUrl(): ?string
    {
        return $this->poster_url;
    }

    public function setPosterUrl(?string $poster_url): self
    {
        $this->poster_url = $poster_url;

        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getBookable(): ?bool
    {
        return $this->bookable;
    }

    public function setBookable(bool $bookable): self
    {
        $this->bookable = $bookable;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(?float $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return Collection|Representation[]
     */
    public function getRepresentations(): Collection
    {
        return $this->representations;
    }

    public function addRepresentation(Representation $representation): self
    {
        if (!$this->representations->contains($representation)) {
            $this->representations[] = $representation;
            $representation->setTheShow($this);
        }

        return $this;
    }

    public function removeRepresentation(Representation $representation): self
    {
        if ($this->representations->contains($representation)) {
            $this->representations->removeElement($representation);
            // set the owning side to null (unless already changed)
            if ($representation->getTheShow() === $this) {
                $representation->setTheShow(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ArtistType[]
     */
    public function getTroupe(): Collection
    {
        return $this->troupe;
    }

    public function addTroupe(ArtistType $troupe): self
    {
        if (!$this->troupe->contains($troupe)) {
            $this->troupe[] = $troupe;
        }

        return $this;
    }

    public function removeTroupe(ArtistType $troupe): self
    {
        if ($this->troupe->contains($troupe)) {
            $this->troupe->removeElement($troupe);
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Form/ShowType.php
<?php

namespace App\Form;

use App\Entity\Show;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;

class ShowType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('poster_url')
            ->add('bookable')
            ->add('price', MoneyType::class)
            ->add('location')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Show::class,
        ]);
    }
}

src/Controller/ShowController.php
<?php

namespace App\Controller;

use App\Entity\Show;
use App\Form\ShowType;
use App\Repository\ShowRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Cocur\Slugify\Slugify;
use App\Entity\Category;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * @Route("/show")
 */
class ShowController extends AbstractController
{
    /**
     * @Route("/", name="show_index", methods={"GET"})
     */
    public function index(ShowRepository $showRepository): Response
    {
        return $this->render('show/index.html.twig', [
            'shows' => $showRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="show_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', NULL, 'Accès interdit');
        
        $show = new Show();
        $form = $this->createForm(ShowType::class, $show);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $slugify = new Slugify();
            $show->setSlug($slugify->slugify($show->getTitle()));
            
            if(is_null($show->getCategory())){
                $repoCategory = $this->getDoctrine()->getRepository(Category::class);
                $categorie = $repoCategory->findOneByName('inconnue');
                
                $show->setCategory($categorie);
            }
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($show);
            $entityManager->flush();

            return $this->redirectToRoute('show_index');
        }

        return $this->render('show/new.html.twig', [
            'show' => $show,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="show_show", methods={"GET"})
     */
    public function show(Show $show): Response
    {
        $repository = $this->getDoctrine()->getManager()->getRepository(Show::class);
        
        $show->author = '';
        
        foreach($show->getTroupe() as $troupe) {
            if($troupe->getType()->getType()=='metteur en scène') {
                $show->author = $troupe->getArtist()->getFirstname()." "
                        .$troupe->getArtist()->getLastname();
                break;
            }
        }
        
        //TODO: $show->author = $repository->findArtistsByType('metteur en scène');
        return $this->render('show/show.html.twig', [
            'show' => $show,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="show_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Show $show): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', NULL, 'Accès interdit');
        
        $form = $this->createForm(ShowType::class, $show);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {           
            if(empty($request->request->get('show')['category'])){
                $repoCategory = $this->getDoctrine()->getRepository(Category::class);
                $categorie = $repoCategory->findOneByName('inconnue');
                
                $show->setCategory($categorie);
            }
            
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('show_index', [
                'id' => $show->getId(),
            ]);
        }

        return $this->render('show/edit.html.twig', [
            'show' => $show,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="show_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Show $show): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', NULL, 'Accès interdit');
        
        if ($this->isCsrfTokenValid('delete'.$show->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($show);
            $entityManager->flush();
        }

        return $this->redirectToRoute('show_index');
    }
    
    /**
     * @Route("/switchBookable/{id}", name="show_bookable_switch", methods={"POST"})
     */
    public function switchBookable(Request $request, Show $show): Response
    {
        $bookable = $request->request->get('bookable');
        $idShow = $request->get('id');
        
        if($bookable=='No') {
            $show->setBookable(true);
        } elseif($bookable=='Yes') {
            $show->setBookable(false);
        }
        
        $this->getDoctrine()->getManager()->flush();
        
        return new JsonResponse(TRUE);
    }
}

templates/show/_delete_form.html.twig
<form method="post" action="{{ path('show_delete', {'id': show.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ show.id) }}">
    <button class="btn">Delete</button>
</form>

templates/show/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Show{% endblock %}

{% block body %}
    <h1>Edit Show</h1>

    {{ include('show/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('show_index') }}">back to list</a>

    {{ include('show/_delete_form.html.twig') }}
{% endblock %}

templates/show/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
{% endblock %}

{% block javascripts %}  
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(function(){
            $('table#liste-shows').DataTable();
            
            //
            $('td.switchable').on('dblclick', function(event) {
                let $td = $(this);
                let idShow = $(this).attr('data-ref');
                let bookable = $(this).text();
                //console.log(idShow);
                const API_URL = 'http://localhost/reservationsSymfony/public/index.php/';
                
                $.ajax({
                  method: "POST",
                  url: API_URL+'show/switchBookable/'+idShow,
                  data: { idShow: idShow, bookable: bookable }
                }).done(function( msg ) {
                    if(bookable=='No') {
                        $td.text('Yes');
                    } else {
                        $td.text('No');
                    }
                }).fail(function(){
                    console.log('Erreur API');
                });
            });
            
        });
    </script>
{% endblock %}

{% block title %}Liste des spectacles{% endblock %}

{% block body %}
    <h1>Liste des spectacles</h1>

    <table id="liste-shows" class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Slug</th>
                <th>Title</th>
                <th>Poster_url</th>
                <th>Bookable</th>
                <th>Price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for show in shows %}
            <tr>
                <td>{{ show.id }}</td>
                <td>{{ show.slug }}</td>
                <td>{{ show.title }}</td>
                <td>{{ show.posterUrl }}</td>
                <td class="switchable" data-ref="{{ show.id }}">{{ show.bookable ? 'Yes' : 'No' }}</td>
                <td>{{ show.price }}</td>
                <td>
                    <a href="{{ path('show_show', {'id': show.id}) }}">show</a>
                {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{ path('show_edit', {'id': show.id}) }}">edit</a>
                    {{ include('show/_delete_form.html.twig') }}
                {% endif %}    
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% if is_granted('ROLE_ADMIN') %}
    <a href="{{ path('show_new') }}">Create new</a>
{% endif %}    
{% endblock %}

templates/show/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Show{% endblock %}

{% block body %}
    <h1>Create new Show</h1>

    {{ include('show/_form.html.twig') }}

    <a href="{{ path('show_index') }}">back to list</a>
{% endblock %}

templates/show/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Show{% endblock %}

{% block body %}
    <h2>{{ show.title }}</h2>

    <div class="card" style="width:18rem;float:left;margin-right: 10px;">
        <figure>
            <img class="card-img-top" src="{{ asset(show.posterUrl) }}" alt="{{ show.title }}">
            <figcaption>de {{ show.author }}</figcaption>
        </figure>
    </div>
    <p class="card-text">{{ show.description }}</p>
    
    <hr style="clear:both; border: 0">
    <ul>
    {% for representation in show.representations %}
        <li>{{ representation.theDate | date("d/m/Y G:i") }}</li>
    {% endfor %}
    </ul>
{% if show.bookable %}
    <a href="#" class="btn btn-primary">Réserver</a>
{% endif %}
        
    <a href="{{ path('show_index') }}">back to list</a>
{% if is_granted('ROLE_ADMIN') %}
    <a href="{{ path('show_edit', {'id': show.id}) }}">edit</a>

    {{ include('show/_delete_form.html.twig') }}
{% endif %}
{% endblock %}